### ISSUE TITLE
Insufficient Setup Instructions in README.md

### ISSUE THREAD

**Issue by harshit4311** [AustralianNationalUniversity/madeline2-server#1]
**Description of the Issue:**
The README file currently lacks comprehensive instructions for setting up the Madeline2 server. It does not provide detailed steps for prerequisites, cloning, building, deploying, and configuring the server. This lack of information makes it difficult for users, especially those unfamiliar with the technology stack, to successfully deploy and run the server.

**Suggested Improvements:**
- Include a detailed section on system requirements, specifying the versions of Java and Tomcat required.
- Provide step-by-step instructions for cloning the repository, building the project using Gradle, and deploying the WAR file to Tomcat.
- Add information on optional configurations for the server, such as adjusting memory settings in Tomcat.
- Offer troubleshooting tips or common issues that might arise during setup.

Providing these details will help new users set up the server more efficiently and reduce potential frustration.

**Additional Context:**
As a user trying to set up the server, I found it challenging to get everything running due to the lack of specific instructions. Adding more detailed guidance would significantly enhance the usability of this project.

**Comment by Philip-Wu** [comment]
Thanks for that harshit, i've also added a full ubuntu installation guide here:

[ubuntu installation guide](https://github.com/AustralianNationalUniversity/madeline2-server/blob/master/INSTALLATION_UBUNTU.md)

I hope that will be help to you
